create table application."user"
(
    id              bigint generated by default as identity
        constraint user_pkey
            primary key,
    creation_date   timestamp,
    login           varchar(255),
    name            varchar(255),
    password        varchar(255),
    role            integer,
    status          integer,
    update_date     timestamp,
    user_creator_id bigint
        constraint fkd3c49170y69x9x9mnmm1q1h0j
            references application."user"
);

alter table application."user"
    owner to postgres;

create table application.audit
(
    id            bigint generated by default as identity
        constraint audit_pkey
            primary key,
    creation_date timestamp,
    description   varchar(255),
    essence_id    bigint,
    essence_name  varchar(255),
    user_id       bigint
        constraint fkai50jigynukoeyjove8u90je9
            references application."user"
);

alter table application.audit
    owner to postgres;

create table application.product
(
    id              bigint generated by default as identity
        constraint product_pkey
            primary key,
    brand           varchar(255),
    calories        double precision,
    carbonates      double precision,
    creation_date   timestamp,
    fats            double precision,
    measure         double precision,
    name            varchar(255),
    protein         double precision,
    update_date     timestamp,
    user_creator_id bigint
        constraint fk1ngowpp5owhpl0inrobk2gs9e
            references application."user"
);

alter table application.product
    owner to postgres;

create table application.ingredient
(
    id            bigint generated by default as identity
        constraint ingredient_pkey
            primary key,
    creation_date timestamp,
    measure       double precision,
    update_date   timestamp,
    product_id    bigint
        constraint fkgg86fhhgm573id99ipfd2br19
            references application.product
);

alter table application.ingredient
    owner to postgres;

create table application.profile
(
    id              bigint generated by default as identity
        constraint profile_pkey
            primary key,
    activity        integer,
    creation_date   timestamp,
    date_of_birth   date,
    height          double precision,
    purpose         integer,
    sex             integer,
    update_date     timestamp,
    weight          double precision,
    user_id         bigint
        constraint fkawh070wpue34wqvytjqr4hj5e
            references application."user",
    user_creator_id bigint
        constraint fkadpwfi4jgdx8bljmaaa8wvsao
            references application."user"
);

alter table application.profile
    owner to postgres;

create table application.recipe
(
    id              bigint generated by default as identity
        constraint recipe_pkey
            primary key,
    creation_date   timestamp,
    name            varchar(255),
    update_date     timestamp,
    user_creator_id bigint
        constraint fkt89bqtyacp5uxkaaj5krjmtfe
            references application."user"
);

alter table application.recipe
    owner to postgres;

create table application.journal
(
    id            bigint generated by default as identity
        constraint journal_pkey
            primary key,
    creation_date timestamp,
    meal_time     integer,
    measure       double precision,
    update_date   timestamp,
    product_id    bigint
        constraint fkf5nlhq5xv18d072biykn44n5v
            references application.product,
    profile_id    bigint
        constraint fkfbvnuw9seakadfaki69892gli
            references application.profile,
    recipe_id     bigint
        constraint fkd3twcgf8s833l0p48njtv1njd
            references application.recipe
);

alter table application.journal
    owner to postgres;

create table application.recipe_ingredients
(
    recipe_id      bigint not null
        constraint fkhnsmvxdlwxqq6x2wbgnoef5gr
            references application.recipe,
    ingredients_id bigint not null
        constraint uk_adlqiu427fu7igg7385el0xjh
            unique
        constraint fkg8ssng1dqiwgcptjptldels74
            references application.ingredient
);

alter table application.recipe_ingredients
    owner to postgres;

create table application.training
(
    id              bigint generated by default as identity
        constraint training_pkey
            primary key,
    calories        double precision not null,
    creation_date   timestamp,
    name            varchar(255),
    update_date     timestamp,
    profile_id      bigint
        constraint fkic66snb2iuxkn0h4epw12ucxp
            references application.profile,
    user_creator_id bigint
        constraint fk7dewhnf1bkmsf4apidf3ofs77
            references application."user"
);

alter table application.training
    owner to postgres;

create table application.weight_measurement
(
    id              bigint generated by default as identity
        constraint weight_measurement_pkey
            primary key,
    creation_date   timestamp,
    update_date     timestamp,
    weight          double precision,
    profile_id      bigint
        constraint fkktp73yjuturaoka5tbhlqo0dm
            references application.profile,
    user_creator_id bigint
        constraint fk3i13bt6jug8ugalhxq17ulwta
            references application."user"
);

alter table application.weight_measurement
    owner to postgres;


